In [1]:
import openai
from llama_index.embeddings import OpenAIEmbedding
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
openai_embedding = OpenAIEmbedding()
embed1 = openai_embedding.get_query_embedding("Who is India's prime minister?")
embed2 = openai_embedding.get_text_embedding("Narendra modi sworn in 2nd time")

embed3 = openai_embedding.get_text_embedding("Draupadi murmu is India's first tribal president")

In [45]:
np.expand_dims(embed1, axis = 0)

array([[ 0.00699447, -0.0006236 , -0.01591846, ..., -0.0255787 ,
        -0.01327808, -0.01602001]])

In [46]:
cosine_similarity(np.expand_dims(embed1, axis = 0), np.array([embed2, embed3]))

array([[0.84810368, 0.8239825 ]])

# Custom Embedding

In [2]:
from InstructorEmbedding import INSTRUCTOR
model = INSTRUCTOR('hkunlp/instructor-large')

/Users/krishansubudhi/miniconda3/envs/gurukul/lib/python3.11/site-packages/InstructorEmbedding/instructor.py:7: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import trange


load INSTRUCTOR_Transformer
max_seq_length  512


In [3]:
embed = model.encode([
    ["Represent the hindu spiritual question for retrieving supporting documents:", "Who built the Ram Temple?"],
    ["Represent the hindu spiritual facts for retrieval:", "Modi built the Ram temple in 2024"],
    ["Represent the hindu spiritual facts for retrieval:", "Ram was born in Ayodhya"]
    ])

In [5]:

cosine_similarity(embed[:1], embed[1:])

array([[0.8875513 , 0.83584654]], dtype=float32)