In [1]:
import openai
from llama_index.embeddings import OpenAIEmbedding
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
openai_embedding = OpenAIEmbedding()
embed1 = openai_embedding.get_query_embedding("Who is India's prime minister?")
embed2 = openai_embedding.get_text_embedding("Narendra modi sworn in 2nd time")

embed3 = openai_embedding.get_text_embedding("Draupadi murmu is India's first tribal president")

In [45]:
np.expand_dims(embed1, axis = 0)

array([[ 0.00699447, -0.0006236 , -0.01591846, ..., -0.0255787 ,
        -0.01327808, -0.01602001]])

In [46]:
cosine_similarity(np.expand_dims(embed1, axis = 0), np.array([embed2, embed3]))

array([[0.84810368, 0.8239825 ]])

# Custom Embedding

In [2]:
from InstructorEmbedding import INSTRUCTOR
model = INSTRUCTOR('hkunlp/instructor-large')

/Users/krishansubudhi/miniconda3/envs/gurukul/lib/python3.11/site-packages/InstructorEmbedding/instructor.py:7: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import trange


load INSTRUCTOR_Transformer
max_seq_length  512


In [3]:
embed = model.encode([
    ["Represent the hindu spiritual question for retrieving supporting documents:", "Who built the Ram Temple?"],
    ["Represent the hindu spiritual facts for retrieval:", "Modi built the Ram temple in 2024"],
    ["Represent the hindu spiritual facts for retrieval:", "Ram was born in Ayodhya"]
    ])

In [5]:

cosine_similarity(embed[:1], embed[1:])

array([[0.8875513 , 0.83584654]], dtype=float32)

### UAE-Large


In [34]:
# pip install angle_emb
from projectgurukul.custom_models import model_utils
device, dtype = model_utils.get_device_and_dtype()
device, dtype

('mps', torch.float16)

In [41]:
from angle_emb import AnglE, Prompts

angle = AnglE.from_pretrained('WhereIsAI/UAE-Large-V1', pooling_strategy='cls').cuda()
angle.set_prompt(prompt=Prompts.C)
vec = angle.encode({'text': 'How about ChatGPT?'}, to_numpy=True)
print(vec)
vecs = angle.encode([{'text': 'ChatGPT is bad.'}, {'text': 'ChatGPT is amazing.'}, {'text': 'Went to school'}], to_numpy=True)
print(vecs)

INFO:AnglE:Prompt is set, the prompt will be automatically applied during the encoding phase. To disable prompt setting, please configure set_prompt(prompt=None)


[[ 0.67591125 -0.41262922  0.05601647 ...  0.00416787  0.24107811
  -0.10354407]]
[[ 0.6656129  -0.48714605  0.5541146  ... -0.16457927  0.0423225
   0.03399242]
 [ 0.7265651  -0.46878216  0.04996064 ... -0.3045764   0.33448562
   0.33442813]
 [ 0.4756281  -0.28673562  0.39295113 ...  0.02098667  0.518445
   0.53710467]]


In [38]:
angle.device

'mps'

In [36]:
device, dtype

('mps', torch.float16)

In [29]:
cosine_similarity(vec, np.array(vecs))

array([[0.8765021 , 0.90052253, 0.48524386]], dtype=float32)

In [6]:
Prompts.C

'Represent this sentence for searching relevant passages: {text}'