In [5]:
import openai
from llama_index.embeddings.openai import OpenAIEmbedding
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
openai_embedding = OpenAIEmbedding(model = "text-embedding-3-small")
embed1 = openai_embedding.get_query_embedding("Who is India's prime minister?")
embed2 = openai_embedding.get_text_embedding("Narendra modi sworn in 2nd time")

embed3 = openai_embedding.get_text_embedding("A cow is an domestic animal")

In [3]:
np.expand_dims(embed1, axis = 0)

array([[ 0.01605923, -0.00779056,  0.02656852, ...,  0.01264677,
         0.03179972, -0.03159348]])

In [11]:
cosine_similarity(np.expand_dims(embed1, axis = 0), np.array([embed2, embed3]))

array([[0.49639595, 0.08184773]])

# Custom Embedding

In [2]:
from InstructorEmbedding import INSTRUCTOR
model = INSTRUCTOR('hkunlp/instructor-large')

/Users/krishansubudhi/miniconda3/envs/gurukul/lib/python3.11/site-packages/InstructorEmbedding/instructor.py:7: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import trange


load INSTRUCTOR_Transformer
max_seq_length  512


In [3]:
embed = model.encode([
    ["Represent the hindu spiritual question for retrieving supporting documents:", "Who built the Ram Temple?"],
    ["Represent the hindu spiritual facts for retrieval:", "Modi built the Ram temple in 2024"],
    ["Represent the hindu spiritual facts for retrieval:", "Ram was born in Ayodhya"]
    ])

In [5]:

cosine_similarity(embed[:1], embed[1:])

array([[0.8875513 , 0.83584654]], dtype=float32)

### UAE-Large


In [34]:
# pip install angle_emb
from projectgurukul.custom_models import model_utils
device, dtype = model_utils.get_device_and_dtype()
device, dtype

('mps', torch.float16)

In [26]:
from angle_emb import AnglE, Prompts

angle = AnglE.from_pretrained('WhereIsAI/UAE-Large-V1', pooling_strategy='cls').cuda()
vec = angle.encode({'text': 'Ram went to forest?'}, to_numpy=True, prompt=Prompts.C)
print(vec)
vecs = angle.encode(['Laxman and his  started his vanbaas.', 'ChatGPT is amazing.',  'Went to school'], to_numpy=True)
print(vecs)

[[ 0.17912504 -0.20322275  0.08699015 ... -0.32702887  0.41425884
   0.3184755 ]]
[[-0.01500864  0.6413412  -0.1157291  ... -0.6342321   0.11338729
   0.6810994 ]
 [ 0.47675014 -0.22714251 -0.4033532  ... -0.4373022   0.55058277
   0.5439574 ]
 [ 0.58175224 -0.23857433  0.02746337 ... -0.08629739  0.49211296
   0.78977615]]


In [27]:
angle.device

'mps'

In [28]:
cosine_similarity(vec, np.array(vecs))

array([[0.49789697, 0.36466   , 0.4161421 ]], dtype=float32)

In [29]:
Prompts.C

'Represent this sentence for searching relevant passages: {text}'